### ISSUE TITLE
BASIC for TCR assembly

### ISSUE THREAD

**Issue by zhouxinseeu** [akds/BASIC#9]
Hi, aakhan !
I am confused that whether BASIC can be used for TCR assembly?
Though there is '-i' to select type, it did not work when I use '-i TCR' for TCR assembly.
Here are my commands:
```
$ cat run.sh
/Personal/zhouxin/software/BASIC/BASIC.py -b /SGRNJ/Public/Software/conda_env/zhouxinT/bin/bowtie2  -SE /SGRNJ02/RandD4/zhouxin/test/TCR_assemble/20210203_HuG_TCR1225_2T/fq/479.fq -g human -i TCR
```
 the error:
```
$ cat run.sh.o413832
Error: reads did not map to hv
Program terminated.
```
Can you help me to solve this problem?
Thank you !

**Comment by dcroote** [comment]
Hi @zhouxinseeu,

BASIC does work with TCR sequences. Try running the command again but adding the `-a` flag (for partial reconstruction). You should see a result then. The error should probably be more informative, but `reads did not map to hv` corresponds to reads not mapping to the TRAV genes (you can see this in the `db/human/TCR/hv` file).

Hope this helps,
Derek

**Comment by zhouxinseeu** [comment]
Hi, aakhan
It works when I add the `-a` flag.
Thank you.
